export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const AUTH_EXPIRED = 'AUTH_EXPIRED';
export const AUTH_FAILED = 'AUTH_FAILED';
